name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npm run db:generate

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    - name: Type check
      run: npx tsc --noEmit

    - name: Build project
      run: npm run build
      env:
        DATABASE_URL: "file:./test.db"
        NEXT_PUBLIC_API_URL: "http://localhost:3000"

    - name: Check for build artifacts
      run: |
        if [ ! -d ".next" ]; then
          echo "Build failed: .next directory not found"
          exit 1
        fi
        echo "✅ Build successful"

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for security vulnerabilities
      run: npm audit --audit-level=high
      continue-on-error: true

    - name: Check package sizes
      run: |
        echo "Checking for large dependencies..."
        npm ls --depth=0 || true
